IF NOT EXISTS (
    SELECT 1
    FROM sys.tables
    WHERE name = 'employments_curated'
)
BEGIN
CREATE TABLE employments_curated (
    prefecture_code INT NOT NULL,
    year INT NOT NULL,
    job_1 INT NULL,
    job_2 INT NULL,
    job_3 INT NULL,
    job_4 INT NULL,
    job_5 INT NULL,
    job_6 INT NULL,
    job_7 INT NULL,
    job_8 INT NULL,
    job_9 INT NULL,
    job_10 INT NULL,
    job_11 INT NULL,
    job_12 INT NULL,
    job_13 INT NULL,
    job_14 INT NULL,
    job_15 INT NULL,
    job_16 INT NULL,
    job_17 INT NULL,
    job_18 INT NULL,
    job_19 INT NULL,
    job_20 INT NULL,
    job_21 INT NULL,
    job_22 INT NULL,
    job_23 INT NULL,
    job_24 INT NULL,
    job_25 INT NULL,
    job_26 INT NULL,
    job_27 INT NULL,
    job_28 INT NULL,
    job_29 INT NULL,
    job_30 INT NULL,
    job_31 INT NULL,
    job_32 INT NULL,
    job_33 INT NULL,
    job_34 INT NULL,
    job_35 INT NULL,
    job_36 INT NULL,
    job_37 INT NULL,
    job_38 INT NULL,
    job_39 INT NULL,
    job_40 INT NULL,
    job_41 INT NULL,
    job_42 INT NULL,
    job_43 INT NULL,
    job_44 INT NULL,
    job_45 INT NULL,
    job_46 INT NULL,
    job_47 INT NULL,
    job_48 INT NULL,
    job_49 INT NULL,
    job_50 INT NULL,
    job_51 INT NULL,
    job_52 INT NULL,
    job_53 INT NULL,
    job_54 INT NULL,
    job_55 INT NULL,
    job_56 INT NULL,
    job_57 INT NULL,
    job_58 INT NULL,
    job_59 INT NULL,
    job_60 INT NULL,
    job_61 INT NULL,
    job_62 INT NULL,
    job_63 INT NULL,
    job_64 INT NULL,
    job_65 INT NULL,
    job_66 INT NULL,
    job_67 INT NULL,
    job_68 INT NULL,
    job_69 INT NULL,
    job_70 INT NULL,
    job_71 INT NULL,
    job_72 INT NULL,
    job_73 INT NULL,
    job_74 INT NULL,
    job_75 INT NULL,
    job_76 INT NULL,
    job_77 INT NULL,
    job_78 INT NULL,
    job_79 INT NULL,
    job_80 INT NULL,
    job_81 INT NULL,
    job_82 INT NULL,
    job_83 INT NULL,
    job_84 INT NULL,
    job_85 INT NULL,
    job_86 INT NULL,
    updated_at DATETIME DEFAULT GETDATE(),
    CONSTRAINT PK_employments_curated PRIMARY KEY (prefecture_code, year)
);
END;
