WITH pivoted AS (
    SELECT
        prefecture_code,
        sex_code,
        generation_code,
        year,
        job_code,
        job_count
    FROM active_job_seekings_landing
),
p AS (
    SELECT
        prefecture_code,
        sex_code,
        generation_code,
        year,
        MAX(CASE WHEN job_code = 1 THEN job_count END) AS job_1,
        MAX(CASE WHEN job_code = 2 THEN job_count END) AS job_2,
        MAX(CASE WHEN job_code = 3 THEN job_count END) AS job_3,
        MAX(CASE WHEN job_code = 4 THEN job_count END) AS job_4,
        MAX(CASE WHEN job_code = 5 THEN job_count END) AS job_5,
        MAX(CASE WHEN job_code = 6 THEN job_count END) AS job_6,
        MAX(CASE WHEN job_code = 7 THEN job_count END) AS job_7,
        MAX(CASE WHEN job_code = 8 THEN job_count END) AS job_8,
        MAX(CASE WHEN job_code = 9 THEN job_count END) AS job_9,
        MAX(CASE WHEN job_code = 10 THEN job_count END) AS job_10,
        MAX(CASE WHEN job_code = 11 THEN job_count END) AS job_11,
        MAX(CASE WHEN job_code = 12 THEN job_count END) AS job_12,
        MAX(CASE WHEN job_code = 13 THEN job_count END) AS job_13,
        MAX(CASE WHEN job_code = 14 THEN job_count END) AS job_14,
        MAX(CASE WHEN job_code = 15 THEN job_count END) AS job_15,
        MAX(CASE WHEN job_code = 16 THEN job_count END) AS job_16,
        MAX(CASE WHEN job_code = 17 THEN job_count END) AS job_17,
        MAX(CASE WHEN job_code = 18 THEN job_count END) AS job_18,
        MAX(CASE WHEN job_code = 19 THEN job_count END) AS job_19,
        MAX(CASE WHEN job_code = 20 THEN job_count END) AS job_20,
        MAX(CASE WHEN job_code = 21 THEN job_count END) AS job_21,
        MAX(CASE WHEN job_code = 22 THEN job_count END) AS job_22,
        MAX(CASE WHEN job_code = 23 THEN job_count END) AS job_23,
        MAX(CASE WHEN job_code = 24 THEN job_count END) AS job_24,
        MAX(CASE WHEN job_code = 25 THEN job_count END) AS job_25,
        MAX(CASE WHEN job_code = 26 THEN job_count END) AS job_26,
        MAX(CASE WHEN job_code = 27 THEN job_count END) AS job_27,
        MAX(CASE WHEN job_code = 28 THEN job_count END) AS job_28,
        MAX(CASE WHEN job_code = 29 THEN job_count END) AS job_29,
        MAX(CASE WHEN job_code = 30 THEN job_count END) AS job_30,
        MAX(CASE WHEN job_code = 31 THEN job_count END) AS job_31,
        MAX(CASE WHEN job_code = 32 THEN job_count END) AS job_32,
        MAX(CASE WHEN job_code = 33 THEN job_count END) AS job_33,
        MAX(CASE WHEN job_code = 34 THEN job_count END) AS job_34,
        MAX(CASE WHEN job_code = 35 THEN job_count END) AS job_35,
        MAX(CASE WHEN job_code = 36 THEN job_count END) AS job_36,
        MAX(CASE WHEN job_code = 37 THEN job_count END) AS job_37,
        MAX(CASE WHEN job_code = 38 THEN job_count END) AS job_38,
        MAX(CASE WHEN job_code = 39 THEN job_count END) AS job_39,
        MAX(CASE WHEN job_code = 40 THEN job_count END) AS job_40,
        MAX(CASE WHEN job_code = 41 THEN job_count END) AS job_41,
        MAX(CASE WHEN job_code = 42 THEN job_count END) AS job_42,
        MAX(CASE WHEN job_code = 43 THEN job_count END) AS job_43,
        MAX(CASE WHEN job_code = 44 THEN job_count END) AS job_44,
        MAX(CASE WHEN job_code = 45 THEN job_count END) AS job_45,
        MAX(CASE WHEN job_code = 46 THEN job_count END) AS job_46,
        MAX(CASE WHEN job_code = 47 THEN job_count END) AS job_47,
        MAX(CASE WHEN job_code = 48 THEN job_count END) AS job_48,
        MAX(CASE WHEN job_code = 49 THEN job_count END) AS job_49,
        MAX(CASE WHEN job_code = 50 THEN job_count END) AS job_50,
        MAX(CASE WHEN job_code = 51 THEN job_count END) AS job_51,
        MAX(CASE WHEN job_code = 52 THEN job_count END) AS job_52,
        MAX(CASE WHEN job_code = 53 THEN job_count END) AS job_53,
        MAX(CASE WHEN job_code = 54 THEN job_count END) AS job_54,
        MAX(CASE WHEN job_code = 55 THEN job_count END) AS job_55,
        MAX(CASE WHEN job_code = 56 THEN job_count END) AS job_56,
        MAX(CASE WHEN job_code = 57 THEN job_count END) AS job_57,
        MAX(CASE WHEN job_code = 58 THEN job_count END) AS job_58,
        MAX(CASE WHEN job_code = 59 THEN job_count END) AS job_59,
        MAX(CASE WHEN job_code = 60 THEN job_count END) AS job_60,
        MAX(CASE WHEN job_code = 61 THEN job_count END) AS job_61,
        MAX(CASE WHEN job_code = 62 THEN job_count END) AS job_62,
        MAX(CASE WHEN job_code = 63 THEN job_count END) AS job_63,
        MAX(CASE WHEN job_code = 64 THEN job_count END) AS job_64,
        MAX(CASE WHEN job_code = 65 THEN job_count END) AS job_65,
        MAX(CASE WHEN job_code = 66 THEN job_count END) AS job_66,
        MAX(CASE WHEN job_code = 67 THEN job_count END) AS job_67,
        MAX(CASE WHEN job_code = 68 THEN job_count END) AS job_68,
        MAX(CASE WHEN job_code = 69 THEN job_count END) AS job_69,
        MAX(CASE WHEN job_code = 70 THEN job_count END) AS job_70,
        MAX(CASE WHEN job_code = 71 THEN job_count END) AS job_71,
        MAX(CASE WHEN job_code = 72 THEN job_count END) AS job_72,
        MAX(CASE WHEN job_code = 73 THEN job_count END) AS job_73,
        MAX(CASE WHEN job_code = 74 THEN job_count END) AS job_74,
        MAX(CASE WHEN job_code = 75 THEN job_count END) AS job_75,
        MAX(CASE WHEN job_code = 76 THEN job_count END) AS job_76,
        MAX(CASE WHEN job_code = 77 THEN job_count END) AS job_77,
        MAX(CASE WHEN job_code = 78 THEN job_count END) AS job_78,
        MAX(CASE WHEN job_code = 79 THEN job_count END) AS job_79,
        MAX(CASE WHEN job_code = 80 THEN job_count END) AS job_80,
        MAX(CASE WHEN job_code = 81 THEN job_count END) AS job_81,
        MAX(CASE WHEN job_code = 82 THEN job_count END) AS job_82,
        MAX(CASE WHEN job_code = 83 THEN job_count END) AS job_83,
        MAX(CASE WHEN job_code = 84 THEN job_count END) AS job_84,
        MAX(CASE WHEN job_code = 85 THEN job_count END) AS job_85,
        MAX(CASE WHEN job_code = 86 THEN job_count END) AS job_86
    FROM pivoted
    GROUP BY prefecture_code, sex_code, generation_code, year
)
MERGE active_job_seekings_curated AS tgt
USING p
ON tgt.prefecture_code = p.prefecture_code
AND tgt.sex_code= p.sex_code
AND tgt.generation_code= p.generation_code
AND tgt.year = p.year
WHEN MATCHED THEN
    UPDATE SET
        tgt.job_1 = p.job_1,
        tgt.job_2 = p.job_2,
        tgt.job_3 = p.job_3,
        tgt.job_4 = p.job_4,
        tgt.job_5 = p.job_5,
        tgt.job_6 = p.job_6,
        tgt.job_7 = p.job_7,
        tgt.job_8 = p.job_8,
        tgt.job_9 = p.job_9,
        tgt.job_10 = p.job_10,
        tgt.job_11 = p.job_11,
        tgt.job_12 = p.job_12,
        tgt.job_13 = p.job_13,
        tgt.job_14 = p.job_14,
        tgt.job_15 = p.job_15,
        tgt.job_16 = p.job_16,
        tgt.job_17 = p.job_17,
        tgt.job_18 = p.job_18,
        tgt.job_19 = p.job_19,
        tgt.job_20 = p.job_20,
        tgt.job_21 = p.job_21,
        tgt.job_22 = p.job_22,
        tgt.job_23 = p.job_23,
        tgt.job_24 = p.job_24,
        tgt.job_25 = p.job_25,
        tgt.job_26 = p.job_26,
        tgt.job_27 = p.job_27,
        tgt.job_28 = p.job_28,
        tgt.job_29 = p.job_29,
        tgt.job_30 = p.job_30,
        tgt.job_31 = p.job_31,
        tgt.job_32 = p.job_32,
        tgt.job_33 = p.job_33,
        tgt.job_34 = p.job_34,
        tgt.job_35 = p.job_35,
        tgt.job_36 = p.job_36,
        tgt.job_37 = p.job_37,
        tgt.job_38 = p.job_38,
        tgt.job_39 = p.job_39,
        tgt.job_40 = p.job_40,
        tgt.job_41 = p.job_41,
        tgt.job_42 = p.job_42,
        tgt.job_43 = p.job_43,
        tgt.job_44 = p.job_44,
        tgt.job_45 = p.job_45,
        tgt.job_46 = p.job_46,
        tgt.job_47 = p.job_47,
        tgt.job_48 = p.job_48,
        tgt.job_49 = p.job_49,
        tgt.job_50 = p.job_50,
        tgt.job_51 = p.job_51,
        tgt.job_52 = p.job_52,
        tgt.job_53 = p.job_53,
        tgt.job_54 = p.job_54,
        tgt.job_55 = p.job_55,
        tgt.job_56 = p.job_56,
        tgt.job_57 = p.job_57,
        tgt.job_58 = p.job_58,
        tgt.job_59 = p.job_59,
        tgt.job_60 = p.job_60,
        tgt.job_61 = p.job_61,
        tgt.job_62 = p.job_62,
        tgt.job_63 = p.job_63,
        tgt.job_64 = p.job_64,
        tgt.job_65 = p.job_65,
        tgt.job_66 = p.job_66,
        tgt.job_67 = p.job_67,
        tgt.job_68 = p.job_68,
        tgt.job_69 = p.job_69,
        tgt.job_70 = p.job_70,
        tgt.job_71 = p.job_71,
        tgt.job_72 = p.job_72,
        tgt.job_73 = p.job_73,
        tgt.job_74 = p.job_74,
        tgt.job_75 = p.job_75,
        tgt.job_76 = p.job_76,
        tgt.job_77 = p.job_77,
        tgt.job_78 = p.job_78,
        tgt.job_79 = p.job_79,
        tgt.job_80 = p.job_80,
        tgt.job_81 = p.job_81,
        tgt.job_82 = p.job_82,
        tgt.job_83 = p.job_83,
        tgt.job_84 = p.job_84,
        tgt.job_85 = p.job_85,
        tgt.job_86 = p.job_86,
        tgt.updated_at  = GETDATE()
WHEN NOT MATCHED THEN
    INSERT (
        prefecture_code, sex_code, generation_code, year,
        job_1, job_2, job_3, job_4, job_5, job_6, job_7, job_8, job_9, job_10,
        job_11, job_12, job_13, job_14, job_15, job_16, job_17, job_18, job_19, job_20,
        job_21, job_22, job_23, job_24, job_25, job_26, job_27, job_28, job_29, job_30,
        job_31, job_32, job_33, job_34, job_35, job_36, job_37, job_38, job_39, job_40,
        job_41, job_42, job_43, job_44, job_45, job_46, job_47, job_48, job_49, job_50,
        job_51, job_52, job_53, job_54, job_55, job_56, job_57, job_58, job_59, job_60,
        job_61, job_62, job_63, job_64, job_65, job_66, job_67, job_68, job_69, job_70,
        job_71, job_72, job_73, job_74, job_75, job_76, job_77, job_78, job_79, job_80,
        job_81, job_82, job_83, job_84, job_85, job_86,
        updated_at 
    )
    VALUES (
        p.prefecture_code, p.sex_code, p.generation_code, p.year,
        p.job_1, p.job_2, p.job_3, p.job_4, p.job_5, p.job_6, p.job_7, p.job_8, p.job_9, p.job_10,
        p.job_11, p.job_12, p.job_13, p.job_14, p.job_15, p.job_16, p.job_17, p.job_18, p.job_19, p.job_20,
        p.job_21, p.job_22, p.job_23, p.job_24, p.job_25, p.job_26, p.job_27, p.job_28, p.job_29, p.job_30,
        p.job_31, p.job_32, p.job_33, p.job_34, p.job_35, p.job_36, p.job_37, p.job_38, p.job_39, p.job_40,
        p.job_41, p.job_42, p.job_43, p.job_44, p.job_45, p.job_46, p.job_47, p.job_48, p.job_49, p.job_50,
        p.job_51, p.job_52, p.job_53, p.job_54, p.job_55, p.job_56, p.job_57, p.job_58, p.job_59, p.job_60,
        p.job_61, p.job_62, p.job_63, p.job_64, p.job_65, p.job_66, p.job_67, p.job_68, p.job_69, p.job_70,
        p.job_71, p.job_72, p.job_73, p.job_74, p.job_75, p.job_76, p.job_77, p.job_78, p.job_79, p.job_80,
        p.job_81, p.job_82, p.job_83, p.job_84, p.job_85, p.job_86,
        GETDATE()
    );
