-- generation_codeへの変換
UPDATE laborforce_generation_industry_employ_landing_raw
SET generation =
    CASE
        WHEN generation = N'15歳以上' THEN 0
        WHEN generation = N'15～19歳' THEN 1
        WHEN generation = N'20～24歳' THEN 2
        WHEN generation = N'25～29歳' THEN 3
        WHEN generation = N'30～34歳' THEN 4
        WHEN generation = N'35～39歳' THEN 5
        WHEN generation = N'40～44歳' THEN 6
        WHEN generation = N'45～49歳' THEN 7
        WHEN generation = N'50～54歳' THEN 8
        WHEN generation = N'55～59歳' THEN 9
        WHEN generation = N'60～64歳' THEN 10
        WHEN generation = N'65歳以上' THEN 11
        ELSE NULL
    END
FROM laborforce_generation_industry_employ_landing_raw;

-- yearの'年'削除
UPDATE laborforce_generation_industry_employ_landing_raw
SET year=
    LEFT(year, 4)
FROM laborforce_generation_industry_employ_landing_raw;

-- landing_rawの内容をcuratedに挿入
WITH src AS (
    SELECT
        TRY_CAST(NULLIF(LTRIM(RTRIM(sex_code)), '') AS INT) AS sex_code,
        TRY_CAST(NULLIF(LTRIM(RTRIM(generation)), '') AS INT) AS generation,
        TRY_CAST(NULLIF(LTRIM(RTRIM(year)), '') AS INT) AS year,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_1)), '') AS INT) AS job_1,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_2)), '') AS INT) AS job_2,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_3)), '') AS INT) AS job_3,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_4)), '') AS INT) AS job_4,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_5)), '') AS INT) AS job_5,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_6)), '') AS INT) AS job_6,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_7)), '') AS INT) AS job_7,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_8)), '') AS INT) AS job_8,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_9)), '') AS INT) AS job_9,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_10)), '') AS INT) AS job_10,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_11)), '') AS INT) AS job_11,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_12)), '') AS INT) AS job_12,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_13)), '') AS INT) AS job_13,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_14)), '') AS INT) AS job_14,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_15)), '') AS INT) AS job_15,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_16)), '') AS INT) AS job_16,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_17)), '') AS INT) AS job_17,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_18)), '') AS INT) AS job_18,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_19)), '') AS INT) AS job_19,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_20)), '') AS INT) AS job_20,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_21)), '') AS INT) AS job_21,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_22)), '') AS INT) AS job_22,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_23)), '') AS INT) AS job_23,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_24)), '') AS INT) AS job_24,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_25)), '') AS INT) AS job_25,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_26)), '') AS INT) AS job_26,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_27)), '') AS INT) AS job_27,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_28)), '') AS INT) AS job_28,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_29)), '') AS INT) AS job_29,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_30)), '') AS INT) AS job_30,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_31)), '') AS INT) AS job_31,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_32)), '') AS INT) AS job_32,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_33)), '') AS INT) AS job_33,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_34)), '') AS INT) AS job_34,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_35)), '') AS INT) AS job_35,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_36)), '') AS INT) AS job_36,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_37)), '') AS INT) AS job_37,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_38)), '') AS INT) AS job_38,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_39)), '') AS INT) AS job_39,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_40)), '') AS INT) AS job_40,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_41)), '') AS INT) AS job_41,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_42)), '') AS INT) AS job_42,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_43)), '') AS INT) AS job_43,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_44)), '') AS INT) AS job_44,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_45)), '') AS INT) AS job_45,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_46)), '') AS INT) AS job_46,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_47)), '') AS INT) AS job_47,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_48)), '') AS INT) AS job_48,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_49)), '') AS INT) AS job_49,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_50)), '') AS INT) AS job_50,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_51)), '') AS INT) AS job_51,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_52)), '') AS INT) AS job_52,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_53)), '') AS INT) AS job_53,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_54)), '') AS INT) AS job_54,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_55)), '') AS INT) AS job_55,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_56)), '') AS INT) AS job_56,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_57)), '') AS INT) AS job_57,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_58)), '') AS INT) AS job_58,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_59)), '') AS INT) AS job_59,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_60)), '') AS INT) AS job_60,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_61)), '') AS INT) AS job_61,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_62)), '') AS INT) AS job_62,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_63)), '') AS INT) AS job_63,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_64)), '') AS INT) AS job_64,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_65)), '') AS INT) AS job_65,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_66)), '') AS INT) AS job_66,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_67)), '') AS INT) AS job_67,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_68)), '') AS INT) AS job_68,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_69)), '') AS INT) AS job_69,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_70)), '') AS INT) AS job_70,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_71)), '') AS INT) AS job_71,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_72)), '') AS INT) AS job_72,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_73)), '') AS INT) AS job_73,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_74)), '') AS INT) AS job_74,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_75)), '') AS INT) AS job_75,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_76)), '') AS INT) AS job_76,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_77)), '') AS INT) AS job_77,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_78)), '') AS INT) AS job_78,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_79)), '') AS INT) AS job_79,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_80)), '') AS INT) AS job_80,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_81)), '') AS INT) AS job_81,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_82)), '') AS INT) AS job_82,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_83)), '') AS INT) AS job_83,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_84)), '') AS INT) AS job_84,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_85)), '') AS INT) AS job_85,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_86)), '') AS INT) AS job_86,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_87)), '') AS INT) AS job_87,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_88)), '') AS INT) AS job_88,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_89)), '') AS INT) AS job_89,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_90)), '') AS INT) AS job_90,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_91)), '') AS INT) AS job_91,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_92)), '') AS INT) AS job_92,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_93)), '') AS INT) AS job_93,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_94)), '') AS INT) AS job_94,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_95)), '') AS INT) AS job_95,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_96)), '') AS INT) AS job_96,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_97)), '') AS INT) AS job_97,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_98)), '') AS INT) AS job_98,
        TRY_CAST(NULLIF(LTRIM(RTRIM(job_99)), '') AS INT) AS job_99
    FROM laborforce_generation_industry_employ_landing_raw
    WHERE sex_code IS NOT NULL
        AND generation IS NOT NULL
        AND year IS NOT NULL
)
MERGE INTO laborforce_generation_industry_employ_curated AS tgt
USING src
    ON tgt.sex_code = src.sex_code
    AND tgt.generation_code = src.generation
    AND tgt.year = src.year

WHEN MATCHED THEN
    UPDATE SET
        tgt.sex_code = src.sex_code,
        tgt.generation_code = src.generation,
        tgt.year = src.year,
        tgt.job_1 = src.job_1,
        tgt.job_2 = src.job_2,
        tgt.job_3 = src.job_3,
        tgt.job_4 = src.job_4,
        tgt.job_5 = src.job_5,
        tgt.job_6 = src.job_6,
        tgt.job_7 = src.job_7,
        tgt.job_8 = src.job_8,
        tgt.job_9 = src.job_9,
        tgt.job_10 = src.job_10,
        tgt.job_11 = src.job_11,
        tgt.job_12 = src.job_12,
        tgt.job_13 = src.job_13,
        tgt.job_14 = src.job_14,
        tgt.job_15 = src.job_15,
        tgt.job_16 = src.job_16,
        tgt.job_17 = src.job_17,
        tgt.job_18 = src.job_18,
        tgt.job_19 = src.job_19,
        tgt.job_20 = src.job_20,
        tgt.job_21 = src.job_21,
        tgt.job_22 = src.job_22,
        tgt.job_23 = src.job_23,
        tgt.job_24 = src.job_24,
        tgt.job_25 = src.job_25,
        tgt.job_26 = src.job_26,
        tgt.job_27 = src.job_27,
        tgt.job_28 = src.job_28,
        tgt.job_29 = src.job_29,
        tgt.job_30 = src.job_30,
        tgt.job_31 = src.job_31,
        tgt.job_32 = src.job_32,
        tgt.job_33 = src.job_33,
        tgt.job_34 = src.job_34,
        tgt.job_35 = src.job_35,
        tgt.job_36 = src.job_36,
        tgt.job_37 = src.job_37,
        tgt.job_38 = src.job_38,
        tgt.job_39 = src.job_39,
        tgt.job_40 = src.job_40,
        tgt.job_41 = src.job_41,
        tgt.job_42 = src.job_42,
        tgt.job_43 = src.job_43,
        tgt.job_44 = src.job_44,
        tgt.job_45 = src.job_45,
        tgt.job_46 = src.job_46,
        tgt.job_47 = src.job_47,
        tgt.job_48 = src.job_48,
        tgt.job_49 = src.job_49,
        tgt.job_50 = src.job_50,
        tgt.job_51 = src.job_51,
        tgt.job_52 = src.job_52,
        tgt.job_53 = src.job_53,
        tgt.job_54 = src.job_54,
        tgt.job_55 = src.job_55,
        tgt.job_56 = src.job_56,
        tgt.job_57 = src.job_57,
        tgt.job_58 = src.job_58,
        tgt.job_59 = src.job_59,
        tgt.job_60 = src.job_60,
        tgt.job_61 = src.job_61,
        tgt.job_62 = src.job_62,
        tgt.job_63 = src.job_63,
        tgt.job_64 = src.job_64,
        tgt.job_65 = src.job_65,
        tgt.job_66 = src.job_66,
        tgt.job_67 = src.job_67,
        tgt.job_68 = src.job_68,
        tgt.job_69 = src.job_69,
        tgt.job_70 = src.job_70,
        tgt.job_71 = src.job_71,
        tgt.job_72 = src.job_72,
        tgt.job_73 = src.job_73,
        tgt.job_74 = src.job_74,
        tgt.job_75 = src.job_75,
        tgt.job_76 = src.job_76,
        tgt.job_77 = src.job_77,
        tgt.job_78 = src.job_78,
        tgt.job_79 = src.job_79,
        tgt.job_80 = src.job_80,
        tgt.job_81 = src.job_81,
        tgt.job_82 = src.job_82,
        tgt.job_83 = src.job_83,
        tgt.job_84 = src.job_84,
        tgt.job_85 = src.job_85,
        tgt.job_86 = src.job_86,
        tgt.job_87 = src.job_87,
        tgt.job_88 = src.job_88,
        tgt.job_89 = src.job_89,
        tgt.job_90 = src.job_90,
        tgt.job_91 = src.job_91,
        tgt.job_92 = src.job_92,
        tgt.job_93 = src.job_93,
        tgt.job_94 = src.job_94,
        tgt.job_95 = src.job_95,
        tgt.job_96 = src.job_96,
        tgt.job_97 = src.job_97,
        tgt.job_98 = src.job_98,
        tgt.job_99 = src.job_99,
        tgt.updated_at = GETDATE()

WHEN NOT MATCHED THEN
    INSERT (
        sex_code,
        generation_code,
        year,
        job_1,
        job_2,
        job_3,
        job_4,
        job_5,
        job_6,
        job_7,
        job_8,
        job_9,
        job_10,
        job_11,
        job_12,
        job_13,
        job_14,
        job_15,
        job_16,
        job_17,
        job_18,
        job_19,
        job_20,
        job_21,
        job_22,
        job_23,
        job_24,
        job_25,
        job_26,
        job_27,
        job_28,
        job_29,
        job_30,
        job_31,
        job_32,
        job_33,
        job_34,
        job_35,
        job_36,
        job_37,
        job_38,
        job_39,
        job_40,
        job_41,
        job_42,
        job_43,
        job_44,
        job_45,
        job_46,
        job_47,
        job_48,
        job_49,
        job_50,
        job_51,
        job_52,
        job_53,
        job_54,
        job_55,
        job_56,
        job_57,
        job_58,
        job_59,
        job_60,
        job_61,
        job_62,
        job_63,
        job_64,
        job_65,
        job_66,
        job_67,
        job_68,
        job_69,
        job_70,
        job_71,
        job_72,
        job_73,
        job_74,
        job_75,
        job_76,
        job_77,
        job_78,
        job_79,
        job_80,
        job_81,
        job_82,
        job_83,
        job_84,
        job_85,
        job_86,
        job_87,
        job_88,
        job_89,
        job_90,
        job_91,
        job_92,
        job_93,
        job_94,
        job_95,
        job_96,
        job_97,
        job_98,
        job_99,
        updated_at
    )
    VALUES (
        src.sex_code,
        src.generation,
        src.year,
        src.job_1,
        src.job_2,
        src.job_3,
        src.job_4,
        src.job_5,
        src.job_6,
        src.job_7,
        src.job_8,
        src.job_9,
        src.job_10,
        src.job_11,
        src.job_12,
        src.job_13,
        src.job_14,
        src.job_15,
        src.job_16,
        src.job_17,
        src.job_18,
        src.job_19,
        src.job_20,
        src.job_21,
        src.job_22,
        src.job_23,
        src.job_24,
        src.job_25,
        src.job_26,
        src.job_27,
        src.job_28,
        src.job_29,
        src.job_30,
        src.job_31,
        src.job_32,
        src.job_33,
        src.job_34,
        src.job_35,
        src.job_36,
        src.job_37,
        src.job_38,
        src.job_39,
        src.job_40,
        src.job_41,
        src.job_42,
        src.job_43,
        src.job_44,
        src.job_45,
        src.job_46,
        src.job_47,
        src.job_48,
        src.job_49,
        src.job_50,
        src.job_51,
        src.job_52,
        src.job_53,
        src.job_54,
        src.job_55,
        src.job_56,
        src.job_57,
        src.job_58,
        src.job_59,
        src.job_60,
        src.job_61,
        src.job_62,
        src.job_63,
        src.job_64,
        src.job_65,
        src.job_66,
        src.job_67,
        src.job_68,
        src.job_69,
        src.job_70,
        src.job_71,
        src.job_72,
        src.job_73,
        src.job_74,
        src.job_75,
        src.job_76,
        src.job_77,
        src.job_78,
        src.job_79,
        src.job_80,
        src.job_81,
        src.job_82,
        src.job_83,
        src.job_84,
        src.job_85,
        src.job_86,
        src.job_87,
        src.job_88,
        src.job_89,
        src.job_90,
        src.job_91,
        src.job_92,
        src.job_93,
        src.job_94,
        src.job_95,
        src.job_96,
        src.job_97,
        src.job_98,
        src.job_99,
        GETDATE()
    );

-- 不要になったlanding_rawテーブルを削除
DROP TABLE laborforce_generation_industry_employ_landing_raw